FROM python:3.7

WORKDIR /usr/src/app

#Modules
COPY ./UserInterface/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /usr/src/app/OpenflowUI
#COPY . .

CMD [ "bash" ]
#CMD [ "python3", "./UserUI.py" ]
